// One icon family for the whole app: Phosphor (duotone by default, set in main.tsx).
// Components keep the names they had, so screens read the same; this file maps them to Phosphor.
export {
  TextAlignLeft as AlignLeft,
  ArrowLeft,
  ArrowUpRight,
  Prohibit as Ban,
  TextB as Bold,
  Check,
  CaretDown as ChevronDown,
  Question as CircleHelp,
  Clock,
  ClockCountdown as Clock3,
  CopySimple as CopyPlus,
  DownloadSimple as Download,
  DotsThreeVertical as EllipsisVertical,
  EyeSlash as EyeOff,
  FilePdf as FileDown,
  Flag,
  TextHTwo as Heading2,
  HighlighterCircle as Highlighter,
  ClockCounterClockwise as History,
  HourglassMedium as Hourglass,
  House,
  ImageSquare as ImagePlus,
  TextItalic as Italic,
  ListDashes as LayoutList,
  Books as Library,
  ListBullets as List,
  ListChecks,
  ListNumbers as ListOrdered,
  CircleNotch as Loader,
  MapPin,
  ArrowsOut as Maximize2,
  ChatCircleText as MessageSquare,
  ChatCircleDots as MessageSquareOff,
  ArrowsIn as Minimize2,
  Moon,
  TreeStructure as Network,
  NotePencil as NotebookPen,
  Palette,
  PencilLine as PenLine,
  PencilSimple as Pencil,
  Play,
  MonitorPlay as PlaySquare,
  Plus,
  ArrowClockwise as Redo2,
  ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search,
  PaperPlaneRight as Send,
  GearSix as Settings,
  ShareNetwork as Share2,
  ShieldCheck,
  Sparkle as Sparkles,
  FilmStrip as SquarePlay,
  Star,
  Note as StickyNote,
  TextStrikethrough as Strikethrough,
  Sun,
  CircleHalf as SunMoon,
  ThumbsUp,
  Trash as Trash2,
  Warning as TriangleAlert,
  TextUnderline as Underline,
  ArrowCounterClockwise as Undo2,
  UserMinus,
  UserPlus,
  UsersThree as UsersRound,
  X,
} from '@phosphor-icons/react'
