"""card reviews for weekly count

Revision ID: 09da5fce7406
Revises: 47a30d1980c7
Create Date: 2026-10-01 09:00:58.255088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09da5fce7406'
down_revision: Union[str, Sequence[str], None] = '47a30d1980c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_reviews_at'), 'card_reviews', ['at'], unique=False)
    op.create_index(op.f('ix_card_reviews_user_id'), 'card_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_reviews_user_id'), table_name='card_reviews')
    op.drop_index(op.f('ix_card_reviews_at'), table_name='card_reviews')
    op.drop_table('card_reviews')
    # ### end Alembic commands ###
