"""not interested and hidden groups

Revision ID: 1bd498d11754
Revises: 35795571fd60
Create Date: 2026-10-05 22:56:38.777152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd498d11754'
down_revision: Union[str, Sequence[str], None] = '35795571fd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('not_interested',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id')
    )
    op.create_index(op.f('ix_not_interested_user_id'), 'not_interested', ['user_id'], unique=False)
    op.add_column('user_settings', sa.Column('hidden_groups', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'hidden_groups')
    op.drop_index(op.f('ix_not_interested_user_id'), table_name='not_interested')
    op.drop_table('not_interested')
    # ### end Alembic commands ###
