"""ai notes

Revision ID: 35795571fd60
Revises: ea739e6e6707
Create Date: 2026-10-05 20:20:12.450709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35795571fd60'
down_revision: Union[str, Sequence[str], None] = 'ea739e6e6707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_notes',
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_try_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('video_id', 'lang')
    )
    op.create_index(op.f('ix_ai_notes_next_try_at'), 'ai_notes', ['next_try_at'], unique=False)
    op.create_index(op.f('ix_ai_notes_updated_at'), 'ai_notes', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_notes_updated_at'), table_name='ai_notes')
    op.drop_index(op.f('ix_ai_notes_next_try_at'), table_name='ai_notes')
    op.drop_table('ai_notes')
    # ### end Alembic commands ###
