"""study companion: notes, progress, cards

Revision ID: 47a30d1980c7
Revises: 63017fec726d
Create Date: 2026-10-01 08:34:22.255976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a30d1980c7'
down_revision: Union[str, Sequence[str], None] = '63017fec726d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_progress',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('position_s', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id')
    )
    op.create_index(op.f('ix_lecture_progress_updated_at'), 'lecture_progress', ['updated_at'], unique=False)
    op.create_index(op.f('ix_lecture_progress_user_id'), 'lecture_progress', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('t_seconds', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_notes_video_id'), 'notes', ['video_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('blanks', sa.JSON(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_due_at'), 'cards', ['due_at'], unique=False)
    op.create_index(op.f('ix_cards_note_id'), 'cards', ['note_id'], unique=False)
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_note_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_due_at'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_notes_video_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_lecture_progress_user_id'), table_name='lecture_progress')
    op.drop_index(op.f('ix_lecture_progress_updated_at'), table_name='lecture_progress')
    op.drop_table('lecture_progress')
    # ### end Alembic commands ###
