"""add vertical to yt_videos

Revision ID: 63017fec726d
Revises: 24f8e1cde0d6
Create Date: 2026-09-29 16:33:06.583471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63017fec726d'
down_revision: Union[str, Sequence[str], None] = '24f8e1cde0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_videos', sa.Column('vertical', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yt_videos', 'vertical')
    # ### end Alembic commands ###
