"""starred videos, notepads, comments cache

Revision ID: ea739e6e6707
Revises: 09da5fce7406
Create Date: 2026-10-02 09:38:55.934999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea739e6e6707'
down_revision: Union[str, Sequence[str], None] = '09da5fce7406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yt_comments',
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_yt_comments_fetched_at'), 'yt_comments', ['fetched_at'], unique=False)
    op.create_table('notepads',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id')
    )
    op.create_index(op.f('ix_notepads_updated_at'), 'notepads', ['updated_at'], unique=False)
    op.create_index(op.f('ix_notepads_user_id'), 'notepads', ['user_id'], unique=False)
    op.create_table('starred_videos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id')
    )
    op.create_index(op.f('ix_starred_videos_created_at'), 'starred_videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_starred_videos_user_id'), 'starred_videos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_starred_videos_user_id'), table_name='starred_videos')
    op.drop_index(op.f('ix_starred_videos_created_at'), table_name='starred_videos')
    op.drop_table('starred_videos')
    op.drop_index(op.f('ix_notepads_user_id'), table_name='notepads')
    op.drop_index(op.f('ix_notepads_updated_at'), table_name='notepads')
    op.drop_table('notepads')
    op.drop_index(op.f('ix_yt_comments_fetched_at'), table_name='yt_comments')
    op.drop_table('yt_comments')
    # ### end Alembic commands ###
